export const ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    REFRESH: "/auth/refresh",
    LOGOUT: "/auth/logout",
    INTROSPECT: "/auth/introspect",
    CHANGE_PASSWORD: "/auth/change-password",
  },
  DOCUMENTS: {
    BASE: "/documents",
    PAGE: "/documents/page",
    NEWEST: "/documents/newest",
    MOST_VIEWED: "/documents/most-viewed",
    SEARCH: "/documents/search",
    SEARCH_ADVANCED: "/documents/search/advanced",
    DELETED: "/documents/deleted",
    byId: (id: string | number) => `/documents/${id}`,
    related: (id: string | number) => `/documents/${id}/related`,
    restore: (id: string | number) => `/documents/restore/${id}`,
    byFolder: (idFolder: string | number) => `/documents/folder/${idFolder}`,
  },
  FOLDERS: {
    BASE: "/folder",
    DELETED: "/folder/deleted",
    byId: (id: string | number) => `/folder/${id}`,
    restore: (id: string | number) => `/folder/restore/${id}`,
    children: (id: string | number) => `/folder/getChildFolder/${id}`,
    allTree: (id: string | number) => `/folder/allTree/${id}`,
  },
  COLLECTIONS: {
    BASE: "/collections",
    byId: (id: string | number) => `/collections/${id}`,
    byType: (type: string) => `/collections/type/${type}`,
    documents: (id: string | number) => `/collections/${id}/documents`,
    addDocument: (idCollection: string | number, idDocument: string | number) =>
      `/collections/${idCollection}/documents/${idDocument}`,
  },
  CATEGORIES: {
    BASE: "/categories",
    ALL: "/categories/getAll",
    byId: (id: string | number) => `/categories/${id}`,
  },
  BORROW: {
    BASE: "/borrow",
    ALL: "/borrow/getAll",
    byId: (id: string | number) => `/borrow/${id}`,
    my: (idAccount: string | number) => `/borrow/my/${idAccount}`,
    approve: (id: string | number) => `/borrow/${id}/approve`,
    reject: (id: string | number) => `/borrow/${id}/reject`,
    borrowed: (id: string | number) => `/borrow/${id}/borrowed`,
    return: (id: string | number) => `/borrow/${id}/return`,
  },
  BOOKS: {
    BASE: "/books",
    ALL: "/books/getAll",
    byId: (id: string | number) => `/books/${id}`,
    byCode: (bookCode: string) => `/books/code/${bookCode}`,
  },
  ACCOUNTS: {
    BASE: "/accounts",
    ALL: "/accounts/getAll",
    byId: (id: string | number) => `/accounts/${id}`,
  },
  ROLES: {
    BASE: "/role",
    ALL: "/role/getAll",
  },
  FILES: {
    upload: (idDocument: string | number) => `/files/upload/${idDocument}`,
    view: (id: string | number) => `/files/view/${id}`,
    thumbnail: "/files/thumbnail",
    stream: (id: string | number) => `/files/stream/${id}`,
    download: (id: string | number) => `/files/download/${id}`,
    byDocument: (idDocument: string | number) =>
      `/files/document/${idDocument}`,
    byId: (id: string | number) => `/files/${id}`,
  },
  STATISTIC: {
    OVERVIEW: "/statistic/overview",
    TOP_VIEWED: "/statistic/topViewed",
    DOCUMENT_BY_TYPE: "/statistic/documentByType",
  },
  AUDIT_LOG: {
    BASE: "/auditlog",
    byUser: (userName: string) => `/auditlog/user/${userName}`,
  },
} as const;
